### PR TITLE
Issue #2 is fixed

### PR DESCRIPTION
**Pull request by harith-hacky03**
Fixed input validation

### CODE REVIEW

**Comment by Abhay2342** [comment]
Screenshot 2024-01-03 091841


Please use the provided preview to verify the functionality of the changes. Currently, when the "Generate" button is clicked without any input, it still results in an error. Kindly check the modifications made to ensure they resolve this issue.

**Comment by harith-hacky03** [comment]
I need access to do that

**Comment by Abhay2342** [comment]
I permitted you.

**Comment by Abhay2342** [comment]
If you encounter challenges in identifying the issue, feel free to reach out. I've already reviewed your forked repository, and I can provide you with a hint to help you troubleshoot the problem.

**Pull request closed without merging**
